# Generated by Django 5.0.4 on 2024-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_anonymousshortify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousshortify',
            name='short_url',
            field=models.URLField(),
        ),
    ]
