# Generated by Django 5.0.4 on 2024-04-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0007_alter_shortify_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortify',
        ),
    ]
