# Generated by Django 5.0.4 on 2024-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0009_anonymousshortify_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousShorti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='AnonymousShortify',
        ),
    ]
