# Generated by Django 5.0.4 on 2024-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0010_anonymousshorti_delete_anonymousshortify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_not_found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
