# Generated by Django 5.0.4 on 2024-04-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0011_page_not_found'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page_not_found',
        ),
    ]
